gxfscatalog:
  base-uri: "http://localhost:8081"
  cert-path: ""
  private-key-path: ""
  verification-method: "did:web:compliance.lab.gaia-x.eu"

gxfswizardapi:
  base-uri: "http://localhost:8085"

keycloak:
  client-id: "federated-catalogue"
  authorization-grant-type: "password"
  base-uri: "http://key-server:8080"
  client-secret: "somesecret"
  gxfscatalog-user: ""
  gxfscatalog-pass: ""
  oidc-base-uri: "${keycloak.base-uri}/realms/gxfscatalog/protocol/openid-connect"
  token-uri: "${keycloak.oidc-base-uri}/token"
  logout-uri: "${keycloak.oidc-base-uri}/logout"

gxfscatalog-library:
  ignore-ssl: false
