gxfscatalog:
  base-uri: "http://localhost:8081"
  cert-path: ""
  private-key-path: ""
  verification-method: "did:web:compliance.lab.gaia-x.eu"

gxfswizardapi:
  base-uri: "http://localhost:8085"

keycloak:
  client-id: "federated-catalogue"
  authorization-grant-type: "password"
  base-uri: "http://key-server:8080"
  client-secret: "somesecret"
  gxfscatalog-user: ""
  gxfscatalog-pass: ""
  oidc-base-uri: "${keycloak.base-uri}/realms/gxfscatalog/protocol/openid-connect"
  token-uri: "${keycloak.oidc-base-uri}/token"
  logout-uri: "${keycloak.oidc-base-uri}/logout"

gxfscatalog-library:
  ignore-ssl: false

gxdch-services:
  max-retries: 3
  retry-delay: 2000
  enforce-compliance: false
  enforce-notary: false
  compliance-base-uris:
    "https://compliance.lab.gaia-x.eu/v1-staging" #,
    #"https://gx-compliance.aruba.it",
    #"https://gx-compliance.gxdch.dih.telekom.com",
    #"https://gx-compliance.airenetworks.es"
  registry-base-uris:
    "https://registry.lab.gaia-x.eu/v1-staging" #,
    #"https://gx-registry.aruba.it",
    #"https://gx-registry.gxdch.dih.telekom.com",
    #"https://gx-registry.airenetworks.es"
  notary-base-uris:
    "https://registrationnumber.notary.lab.gaia-x.eu/development" #,
    #"https://gx-notary.aruba.it",
    #"https://gx-notary.gxdch.dih.telekom.com",
    #"https://gx-notary.airenetworks.es"